/*
 * This source file was generated by the Gradle 'init' task
 */
package usace.cc.plugin.api;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("asdfasdfasdf");

        return true;
    }
}
