// /*
//  * This source file was generated by the Gradle 'init' task
//  */
// package usace.cc.plugin.api;

// import org.junit.jupiter.api.Test;
// import static org.junit.jupiter.api.Assertions.*;

// class LibraryTest {
//     @Test void someLibraryMethodReturnsTrue() {
//         var val1=System.getenv("VAR1");
//         System.out.println(val1);
//         Library classUnderTest = new Library();
//         assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
//     }
// }
